× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
_______resolve____________________
스캔 오류: 'BLEDevice' object has no attribute 'rssi'
❌ 블루투스 연결 실패
--------------------------------------------------
Traceback (most recent call last):
  File "/home/aisl/deepcare/sensor/bluetooth_test.py", line 31, in <module>
    asyncio.run(find_pico_devices())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aisl/deepcare/sensor/bluetooth_test.py", line 11, in find_pico_devices
    device_name = device.name or ""
                  ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
-------------------------------------------------
bleak error
=== Bleak 라이브러리 정보 ===
Traceback (most recent call last):
  File "/home/aisl/deepcare/sensor/bleak_test.py", line 6, in <module>
    print(f"버전: {bleak.__version__}")
                 ^^^^^^^^^^^^^^^^^
AttributeError: module 'bleak' has no attribute '__version__'



